export const ROLES_CONSTANT = {
  ADMIN: "ADMIN",
  SUBADMIN: "SUBADMIN",
  USER: "USER",
  MANUFACTURER: "MANUFACTURER",
  DISTRIBUTER: "DISTRIBUTER",
  DEALER: "DEALER",
  APPROVERS: "APPROVERS"
}

export  const APPROVED_STATUS = {
    APPROVED :"APPROVED",
    PENDING :"PENDING",
    REJECTED :"REJECTED"
}
